# Generated by Django 2.0.1 on 2018-02-01 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180201_0356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-priority', 'title'], 'verbose_name': 'Todo', 'verbose_name_plural': 'Todos'},
        ),
    ]
