# Generated by Django 2.0.1 on 2018-02-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180201_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Baixa'), (2, 'Normal'), (3, 'Alta')], default=2),
        ),
    ]
