# Generated by Django 2.0.1 on 2018-02-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180203_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[('Baixa', 1), ('Normal', 2), ('Alta', 3)], default=2),
        ),
    ]
