# Generated by Django 2.0.1 on 2018-02-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180203_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[('Baixa', 'BAIXA'), ('Normal', 'NORMAL'), ('Alta', 'ALTA')]),
        ),
    ]
