# Generated by Django 2.0.1 on 2018-02-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180203_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('Baixa', 'BAIXA'), ('Normal', 'NORMAL'), ('Alta', 'ALTA')], max_length=6),
        ),
    ]
