# Generated by Django 2.0.1 on 2018-02-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180203_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('Baixa', 'Baixa'), ('Normal', 'Normal'), ('Alta', 'Alta')], default='NORMAL', max_length=6),
        ),
    ]
