# Generated by Django 2.0.1 on 2018-02-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20180203_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('Baixa', 'Baixa'), ('Normal', 'Normal'), ('Alta', 'Alta')], max_length=6),
        ),
    ]
