# Generated by Django 2.0.1 on 2018-02-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20180203_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Baixa'), (2, 'Normal'), (3, 'Alta')], default=2),
        ),
    ]
