# Generated by Django 2.0.1 on 2018-02-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20180203_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-priority', 'created_date']},
        ),
    ]
